// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxQ7FPg1UWx02ZLxi7FUa4WRTmeuyKj0',
    appId: '1:992873239256:web:d41001f95d0c67bdeffdad',
    messagingSenderId: '992873239256',
    projectId: 'smart-inventory-app-82d9d',
    authDomain: 'smart-inventory-app-82d9d.firebaseapp.com',
    storageBucket: 'smart-inventory-app-82d9d.firebasestorage.app',
    measurementId: 'G-HDLPWJKMW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMNwVyRteba_ToFE4K01TJtlrCdtrkLQ',
    appId: '1:992873239256:android:2c2ed27633eaf7d7effdad',
    messagingSenderId: '992873239256',
    projectId: 'smart-inventory-app-82d9d',
    storageBucket: 'smart-inventory-app-82d9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFhTrloEpxLxaV5mINtZTjHJdfafM7m_Y',
    appId: '1:992873239256:ios:9256e87bd31ef35aeffdad',
    messagingSenderId: '992873239256',
    projectId: 'smart-inventory-app-82d9d',
    storageBucket: 'smart-inventory-app-82d9d.firebasestorage.app',
    iosBundleId: 'com.example.smartInventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFhTrloEpxLxaV5mINtZTjHJdfafM7m_Y',
    appId: '1:992873239256:ios:9256e87bd31ef35aeffdad',
    messagingSenderId: '992873239256',
    projectId: 'smart-inventory-app-82d9d',
    storageBucket: 'smart-inventory-app-82d9d.firebasestorage.app',
    iosBundleId: 'com.example.smartInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRxQ7FPg1UWx02ZLxi7FUa4WRTmeuyKj0',
    appId: '1:992873239256:web:7ab4a8c899a4cfd8effdad',
    messagingSenderId: '992873239256',
    projectId: 'smart-inventory-app-82d9d',
    authDomain: 'smart-inventory-app-82d9d.firebaseapp.com',
    storageBucket: 'smart-inventory-app-82d9d.firebasestorage.app',
    measurementId: 'G-QKLRJFBW6L',
  );
}
